#!/bin/sh

DOTFILES_DIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"

ln -sf "${DOTFILES_DIR}/.emacs.d" ~
ln -sf "${DOTFILES_DIR}/.tmux.conf" ~
ln -sf "${DOTFILES_DIR}/.gitconfig" ~

mkdir -p ~/.config/htop
ln -sf "${DOTFILES_DIR}/htoprc" ~/.config/htop

sudo apt update
sudo apt install -y emacs time

cat "${DOTFILES_DIR}/.zshrc" >> ~/.zshrc
