#!/bin/sh

rm -rf ~/.emacs.d 2>&1 > /dev/null
rm -rf ~/.tmux.conf 2>&1 > /dev/null
rm -rf ~/.gitconfig 2>&1 > /dev/null

ln -s ~/dotfiles/.emacs.d ~
ln -s ~/dotfiles/.tmux.conf ~
ln -s ~/dotfiles/.gitconfig ~

cat << EOF >> ~/.zshrc

export EDITOR=nano
export GIT_EDITOR=nano
EOF
