;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-hungry-delete-forward
        c-indent-line-or-region
        indent-for-tab-command
        kill-region
        tab-to-tab-stop
        ))

(setq mc/cmds-to-run-once
      '(
        Buffer-menu-delete
        Buffer-menu-execute
        c-toggle-electric-state
        ido-find-file
        ))
